/**
 * ČNB calls these entities "Country",
 * but in fact it also includes institutions like EMU or IMF...
 */
export enum CnbCountryName {
  Australia = 'Australia',
  Brazil = 'Brazil',
  Canada = 'Canada',
  China = 'China',
  Denmark = 'Denmark',
  EMU = 'EMU',
  Hongkong = 'Hongkong',
  Hungary = 'Hungary',
  Iceland = 'Iceland',
  IMF = 'IMF',
  India = 'India',
  Indonesia = 'Indonesia',
  Israel = 'Israel',
  Japan = 'Japan',
  Malaysia = 'Malaysia',
  Mexico = 'Mexico',
  NewZealand = 'New Zealand',
  Norway = 'Norway',
  Philippines = 'Philippines',
  Poland = 'Poland',
  Romania = 'Romania',
  Singapore = 'Singapore',
  SouthAfrica = 'South Africa',
  SouthKorea = 'South Korea',
  Sweden = 'Sweden',
  Switzerland = 'Switzerland',
  Thailand = 'Thailand',
  Turkey = 'Turkey',
  UnitedKingdom = 'United Kingdom',
  USA = 'USA',
}

export const cnbCountryNameToFlagEmojiMap: Record<CnbCountryName, string> = {
  [CnbCountryName.Australia]: '🇦🇺',
  [CnbCountryName.Brazil]: '🇧🇷',
  [CnbCountryName.Canada]: '🇨🇦',
  [CnbCountryName.China]: '🇨🇳',
  [CnbCountryName.Denmark]: '🇩🇰',
  [CnbCountryName.EMU]: '🇪🇺',
  [CnbCountryName.Hongkong]: '🇭🇰',
  [CnbCountryName.Hungary]: '🇭🇺',
  [CnbCountryName.Iceland]: '🇮🇸',
  [CnbCountryName.IMF]: '🌐',
  [CnbCountryName.India]: '🇮🇳',
  [CnbCountryName.Indonesia]: '🇮🇩',
  [CnbCountryName.Israel]: '🇮🇱',
  [CnbCountryName.Japan]: '🇯🇵',
  [CnbCountryName.Malaysia]: '🇲🇾',
  [CnbCountryName.Mexico]: '🇲🇽',
  [CnbCountryName.NewZealand]: '🇳🇿',
  [CnbCountryName.Norway]: '🇳🇴',
  [CnbCountryName.Philippines]: '🇵🇭',
  [CnbCountryName.Poland]: '🇵🇱',
  [CnbCountryName.Romania]: '🇷🇴',
  [CnbCountryName.Singapore]: '🇸🇬',
  [CnbCountryName.SouthAfrica]: '🇿🇦',
  [CnbCountryName.SouthKorea]: '🇰🇷',
  [CnbCountryName.Sweden]: '🇸🇪',
  [CnbCountryName.Switzerland]: '🇨🇭',
  [CnbCountryName.Thailand]: '🇹🇭',
  [CnbCountryName.Turkey]: '🇹🇷',
  [CnbCountryName.UnitedKingdom]: '🇬🇧',
  [CnbCountryName.USA]: '🇺🇸',
};

export enum CnbCurrencyCode {
  AUD = 'AUD',
  BRL = 'BRL',
  CAD = 'CAD',
  CNY = 'CNY',
  DKK = 'DKK',
  EUR = 'EUR',
  HKD = 'HKD',
  HUF = 'HUF',
  ISK = 'ISK',
  XDR = 'XDR',
  INR = 'INR',
  IDR = 'IDR',
  ILS = 'ILS',
  JPY = 'JPY',
  MYR = 'MYR',
  MXN = 'MXN',
  NZD = 'NZD',
  NOK = 'NOK',
  PHP = 'PHP',
  PLN = 'PLN',
  RON = 'RON',
  SGD = 'SGD',
  ZAR = 'ZAR',
  KRW = 'KRW',
  SEK = 'SEK',
  CHF = 'CHF',
  THB = 'THB',
  TRY = 'TRY',
  GBP = 'GBP',
  USD = 'USD',
}
